// VC:
//         BARRIER;
// 
//         FETCH:
//                 FETCH_TYPE.VTX_FETCH_VERTEX_DATA SRC_SEL_X.SEL_X MEGA_FETCH_COUNT(7);
//                 DST_GRP(1) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_0 DST_SEL_W.SEL_1 DATA_FORMAT.FMT_32_32_FLOAT NUM_FORMAT_ALL.NUM_FORMAT_SCALED FORMAT_COMP_ALL.FORMAT_COMP_SIGNED;
//                 MEGA_FETCH;


NOP: BARRIER;

ALU: BARRIER;
/*        MOV:
                SRC0_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_X LAST;
		0x00000000;
		0x00000000;*/
        MOV:
                SRC0_SEL.ALU_SRC_HW_WAVE_ID SRC0_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_X;
/*        MOV:
                SRC0_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_Y LAST;
		0x00000001;
		0x00000001;
        MOV:
                SRC0_SEL.ALU_SRC_1_INT SRC1_SEL.ALU_SRC_1_INT SRC0_CHAN.CHAN_Y SRC1_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_Z LAST;
        MOV:
                SRC0_SEL.ALU_SRC_1_INT SRC1_SEL.ALU_SRC_1_INT SRC0_CHAN.CHAN_Y SRC1_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_W LAST;*/
		
        MOV:
                SRC0_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_X LAST;
                WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_X;
		0xb00bface;
		0x00000000;
        MOV:
                SRC0_SEL.ALU_SRC_HW_WAVE_ID SRC0_CHAN.CHAN_Y LAST;
                WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_Y;
		0xb000face;
		0x00000000;

MEM_RAT_CACHELESS:
        RAT_ID(11) RAT_INST.EXPORT_RAT_INST_STORE_RAW RAT_INDEX_MODE.CF_INDEX_NONE TYPE(1) RW_GPR(1) INDEX_GPR(0);
        COMP_MASK(1) BARRIER;
	
// WAIT_ACK: BARRIER COUNT(0);

KILL: BARRIER;

// NOP: END_OF_PROGRAM;

EXPORT_DONE:
        ARRAY_BASE(60) TYPE.EXPORT_POS RW_GPR(1) INDEX_GPR(0);
        SEL_X.SEL_X SEL_Y.SEL_Y SEL_Z.SEL_Z SEL_W.SEL_W BARRIER;

EXPORT_DONE:
        TYPE.EXPORT_PARAM RW_GPR(0) INDEX_GPR(0);
        SEL_X.SEL_X SEL_Y.SEL_Y SEL_Z.SEL_Z SEL_W.SEL_W BARRIER END_OF_PROGRAM;


end;
