# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rakadam/Projects/radeon_compute

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rakadam/Projects/radeon_compute

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rakadam/Projects/radeon_compute/CMakeFiles /home/rakadam/Projects/radeon_compute/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rakadam/Projects/radeon_compute/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named expr

# Build rule for target.
expr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expr
.PHONY : expr

# fast build rule for target.
expr/fast:
	$(MAKE) -f CMakeFiles/expr.dir/build.make CMakeFiles/expr.dir/build
.PHONY : expr/fast

#=============================================================================
# Target rules for targets named r800_compute

# Build rule for target.
r800_compute: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 r800_compute
.PHONY : r800_compute

# fast build rule for target.
r800_compute/fast:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/build
.PHONY : r800_compute/fast

#=============================================================================
# Target rules for targets named test_01

# Build rule for target.
test_01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_01
.PHONY : test_01

# fast build rule for target.
test_01/fast:
	$(MAKE) -f tests/01_basic_no_shader/CMakeFiles/test_01.dir/build.make tests/01_basic_no_shader/CMakeFiles/test_01.dir/build
.PHONY : test_01/fast

#=============================================================================
# Target rules for targets named test_02

# Build rule for target.
test_02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_02
.PHONY : test_02

# fast build rule for target.
test_02/fast:
	$(MAKE) -f tests/02_noop_shader/CMakeFiles/test_02.dir/build.make tests/02_noop_shader/CMakeFiles/test_02.dir/build
.PHONY : test_02/fast

#=============================================================================
# Target rules for targets named test_03

# Build rule for target.
test_03: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_03
.PHONY : test_03

# fast build rule for target.
test_03/fast:
	$(MAKE) -f tests/03_single_copy/CMakeFiles/test_03.dir/build.make tests/03_single_copy/CMakeFiles/test_03.dir/build
.PHONY : test_03/fast

#=============================================================================
# Target rules for targets named test_04

# Build rule for target.
test_04: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_04
.PHONY : test_04

# fast build rule for target.
test_04/fast:
	$(MAKE) -f tests/04_multi_copy/CMakeFiles/test_04.dir/build.make tests/04_multi_copy/CMakeFiles/test_04.dir/build
.PHONY : test_04/fast

#=============================================================================
# Target rules for targets named test_05

# Build rule for target.
test_05: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_05
.PHONY : test_05

# fast build rule for target.
test_05/fast:
	$(MAKE) -f tests/05_atomics/CMakeFiles/test_05.dir/build.make tests/05_atomics/CMakeFiles/test_05.dir/build
.PHONY : test_05/fast

#=============================================================================
# Target rules for targets named test_06

# Build rule for target.
test_06: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_06
.PHONY : test_06

# fast build rule for target.
test_06/fast:
	$(MAKE) -f tests/06_loop/CMakeFiles/test_06.dir/build.make tests/06_loop/CMakeFiles/test_06.dir/build
.PHONY : test_06/fast

cs_image.o: cs_image.cpp.o
.PHONY : cs_image.o

# target to build an object file
cs_image.cpp.o:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/cs_image.cpp.o
.PHONY : cs_image.cpp.o

cs_image.i: cs_image.cpp.i
.PHONY : cs_image.i

# target to preprocess a source file
cs_image.cpp.i:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/cs_image.cpp.i
.PHONY : cs_image.cpp.i

cs_image.s: cs_image.cpp.s
.PHONY : cs_image.s

# target to generate assembly for a file
cs_image.cpp.s:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/cs_image.cpp.s
.PHONY : cs_image.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/expr.dir/build.make CMakeFiles/expr.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/expr.dir/build.make CMakeFiles/expr.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/expr.dir/build.make CMakeFiles/expr.dir/main.cpp.s
.PHONY : main.cpp.s

r800_state.o: r800_state.cpp.o
.PHONY : r800_state.o

# target to build an object file
r800_state.cpp.o:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/r800_state.cpp.o
.PHONY : r800_state.cpp.o

r800_state.i: r800_state.cpp.i
.PHONY : r800_state.i

# target to preprocess a source file
r800_state.cpp.i:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/r800_state.cpp.i
.PHONY : r800_state.cpp.i

r800_state.s: r800_state.cpp.s
.PHONY : r800_state.s

# target to generate assembly for a file
r800_state.cpp.s:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/r800_state.cpp.s
.PHONY : r800_state.cpp.s

radeon_cs.o: radeon_cs.cpp.o
.PHONY : radeon_cs.o

# target to build an object file
radeon_cs.cpp.o:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/radeon_cs.cpp.o
.PHONY : radeon_cs.cpp.o

radeon_cs.i: radeon_cs.cpp.i
.PHONY : radeon_cs.i

# target to preprocess a source file
radeon_cs.cpp.i:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/radeon_cs.cpp.i
.PHONY : radeon_cs.cpp.i

radeon_cs.s: radeon_cs.cpp.s
.PHONY : radeon_cs.s

# target to generate assembly for a file
radeon_cs.cpp.s:
	$(MAKE) -f CMakeFiles/r800_compute.dir/build.make CMakeFiles/r800_compute.dir/radeon_cs.cpp.s
.PHONY : radeon_cs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... expr"
	@echo "... r800_compute"
	@echo "... rebuild_cache"
	@echo "... test_01"
	@echo "... test_02"
	@echo "... test_03"
	@echo "... test_04"
	@echo "... test_05"
	@echo "... test_06"
	@echo "... cs_image.o"
	@echo "... cs_image.i"
	@echo "... cs_image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... r800_state.o"
	@echo "... r800_state.i"
	@echo "... r800_state.s"
	@echo "... radeon_cs.o"
	@echo "... radeon_cs.i"
	@echo "... radeon_cs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

