/*
 * Copyright 2011 StreamNovation Ltd. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of
 *       conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list
 *       of conditions and the following disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY StreamNovation Ltd. ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL StreamNovation Ltd. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those of the
 * authors and should not be interpreted as representing official policies, either expressed
 * or implied, of StreamNovation Ltd.
 *
 *
 * Author(s):
 *          Adam Rak <adam.rak@streamnovation.com>
 *          Carl-Philip Hänsch <s3734770@mail.zih.tu-dresden.de>
 *
 *
 */

// ToDo: Thread group init
// gpr(0) = x, y, matwid*x, matwid*y
// gpr(1) = meta_x, meta_y
// gpr(2) = matwid*x+y, matwid*x
// gpr(3) = matwid*4y+0123
// gpr(4) = a[x, 4k+0123]
// gpr(5) = result[4]
// gpr(6,7,8,9) = b[4y+0123, 4k+0123]
ALU:
  KCACHE_BANK0(0) KCACHE_MODE0.CF_KCACHE_LOCK_1;
  BARRIER;

  // calc position x y from x and meta_x
  MULLO_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_X;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_Y;
    LAST;
    WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_X; // gpr(1).x*=dividor
  MULLO_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_Y;
    LAST;
    WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_Y; // gpr(1).y*=dividor

  ADD_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_X; // gpr(0).x = x
    LAST;
  MULLO_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X;
    LAST;
    WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_Y; // gpr(0).y = 4*y
    0x4
    0x4;
  ADD_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_Y;
    WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_Y; // gpr(0).y = 4*y
    LAST;

  // calc output position to write to
  MULLO_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_X;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_Y; // gpr(2).y = x*matwid
    LAST;

  MULLO_INT:
    // gpr(3) = 4*y*matwid + {0,1,2,3}*matwid
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_X; // gpr(3).x = 4y*matwid
    LAST;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_X;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_Y;
    LAST;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_Z;
    LAST;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.Kcache_bank0(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_W;
    LAST;

  // prepare sum in gpr(5)
  MOV:
    SRC0_SEL.ALU_SRC_0 SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_X;
  MOV:
    SRC0_SEL.ALU_SRC_0 SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_Y;
  MOV:
    SRC0_SEL.ALU_SRC_0 SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_Z;
  MOV:
    SRC0_SEL.ALU_SRC_0 SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_W;
    LAST;


  ADD_INT:
    SRC0_SEL.GPR(2) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_Y;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_X;
    LAST; // gpr(2).y = target position of the calculated 4x element


  MOV:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_Z
    WRITE_MASK DST_GPR(7) DST_CHAN.CHAN_X;
  MOV:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_W
    WRITE_MASK DST_GPR(7) DST_CHAN.CHAN_Y;
  ADD_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_Z
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X
    WRITE_MASK DST_GPR(7) DST_CHAN.CHAN_Z;
  ADD_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_W
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X
    LAST;
    WRITE_MASK DST_GPR(7) DST_CHAN.CHAN_W;
    0x4;
    0x0;

LOOP_START:
       ADDR(@1);
       CF_CONST(0);
       BARRIER;
@2

TC:
  BARRIER;

  FETCH: // fetch a[]
    FETCH_TYPE.VTX_FETCH_NO_INDEX_OFFSET BUFFER_ID(0) SRC_GPR(2) SRC_SEL_X.SEL_Y MEGA_FETCH_COUNT(15);
    DST_GPR(4) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_Z DST_SEL_W.SEL_W USE_CONST_FIELDS;
    MEGA_FETCH;

  // fetch b[]
  FETCH:
    FETCH_TYPE.VTX_FETCH_NO_INDEX_OFFSET BUFFER_ID(1) SRC_GPR(3) SRC_SEL_X.SEL_X MEGA_FETCH_COUNT(15);
    DST_GPR(6) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_Z DST_SEL_W.SEL_W USE_CONST_FIELDS;
    MEGA_FETCH;
  FETCH:
    FETCH_TYPE.VTX_FETCH_NO_INDEX_OFFSET BUFFER_ID(1) SRC_GPR(3) SRC_SEL_X.SEL_Y MEGA_FETCH_COUNT(15);
    DST_GPR(7) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_Z DST_SEL_W.SEL_W USE_CONST_FIELDS;
    MEGA_FETCH;
  FETCH:
    FETCH_TYPE.VTX_FETCH_NO_INDEX_OFFSET BUFFER_ID(1) SRC_GPR(3) SRC_SEL_X.SEL_Z MEGA_FETCH_COUNT(15);
    DST_GPR(8) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_Z DST_SEL_W.SEL_W USE_CONST_FIELDS;
    MEGA_FETCH;
  FETCH:
    FETCH_TYPE.VTX_FETCH_NO_INDEX_OFFSET BUFFER_ID(1) SRC_GPR(3) SRC_SEL_X.SEL_W MEGA_FETCH_COUNT(15);
    DST_GPR(9) DST_SEL_X.SEL_X DST_SEL_Y.SEL_Y DST_SEL_Z.SEL_Z DST_SEL_W.SEL_W USE_CONST_FIELDS;
    MEGA_FETCH;

ALU:
  BARRIER;

  // 4y+0
  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(6) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(6) DST_CHAN.CHAN_X;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(6) SRC1_CHAN.CHAN_Y;
    DST_CHAN.CHAN_Y;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(6) SRC1_CHAN.CHAN_Z;
    DST_CHAN.CHAN_Z;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(6) SRC1_CHAN.CHAN_W;
    DST_CHAN.CHAN_W;
    LAST;

  // 4y+1
  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(7) SRC1_CHAN.CHAN_X;
    DST_CHAN.CHAN_X;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(7) SRC1_CHAN.CHAN_Y;
    WRITE_MASK DST_GPR(7) DST_CHAN.CHAN_Y;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(7) SRC1_CHAN.CHAN_Z;
    DST_CHAN.CHAN_Z;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(7) SRC1_CHAN.CHAN_W;
    DST_CHAN.CHAN_W;
    LAST;

  // 4y+2
  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(8) SRC1_CHAN.CHAN_X;
    DST_CHAN.CHAN_X;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(8) SRC1_CHAN.CHAN_Y;
    DST_CHAN.CHAN_Y;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(8) SRC1_CHAN.CHAN_Z;
    WRITE_MASK DST_GPR(8) DST_CHAN.CHAN_Z;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(8) SRC1_CHAN.CHAN_W;
    DST_CHAN.CHAN_W;
    LAST;

  // 4y+3
  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(9) SRC1_CHAN.CHAN_X;
    DST_CHAN.CHAN_X;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(9) SRC1_CHAN.CHAN_Y;
    DST_CHAN.CHAN_Y;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(9) SRC1_CHAN.CHAN_Z;
    DST_CHAN.CHAN_Z;

  DOT4_IEEE:
    SRC0_SEL.GPR(4) SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(9) SRC1_CHAN.CHAN_W;
    WRITE_MASK DST_GPR(9) DST_CHAN.CHAN_W;
    LAST;

  // and now result+=tmp-result
  ADD:
    SRC0_SEL.GPR(5) SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(6) SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_X;
    LAST;
  ADD:
    SRC0_SEL.GPR(5) SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(7) SRC1_CHAN.CHAN_Y;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_Y;
    LAST;
  ADD:
    SRC0_SEL.GPR(5) SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(8) SRC1_CHAN.CHAN_Z;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_Z;
    LAST;
  ADD:
    SRC0_SEL.GPR(5) SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(9) SRC1_CHAN.CHAN_W;
    WRITE_MASK DST_GPR(5) DST_CHAN.CHAN_W;
    LAST;

  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_X
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_X;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_Y
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_Y
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_Y;
    LAST;
    0x4;
    0x4;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_Z
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_Z;
  ADD_INT:
    SRC0_SEL.GPR(3) SRC0_CHAN.CHAN_W
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_Y
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_W;
    LAST;
    0x4;
    0x4;
  ADD_INT:
    SRC0_SEL.GPR(2) SRC0_CHAN.CHAN_Y
    SRC1_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_Y
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_Y;
    LAST;
    0x4;
    0x4;

LOOP_END:
         ADDR(@2);
         BARRIER;

@1


MEM_RAT_CACHELESS:
  RAT_ID(11) RAT_INST.EXPORT_RAT_INST_STORE_RAW TYPE(1) RW_GPR(5) INDEX_GPR(2) ELEM_SIZE(0);
  COMP_MASK(15) BARRIER ARRAY_SIZE(0);

NOP:
  BARRIER END_OF_PROGRAM;

end;
